target:	hw1

hw1_lib:	hw1_lib.h	hw1_lib.cpp 
			g++	-std=c++11	-c	hw1_lib.cpp

hw1_main:	hw1_main	hw1_lib
			g++ -std=c++11	-c	hw1_main.cpp

hw1:	hw1_main	hw1_lib
		g++ -std=c++11	hw1_lib.o	hw1_main.cpp	-o	hw1

clean:	
		rm hw1