target:	hw6

main:	GTUVector.h GTUSet.h GTUArray.h GTUIterator.h GTUIteratorConst.h Iterable.h	Exceptions.h
		g++ -std=c++11 -c hw6_main.cpp

hw6:	main
		g++ -std=c++11 hw6_main.cpp	-o hw6
clean:
		rm hw6 *.o